// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pt-PT'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	errors: {
		users: {
			signup: {
				/**
				 * U​s​e​r​ ​w​i​t​h​ ​e​m​a​i​l​ ​{​e​m​a​i​l​}​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
				 * @param {string} email
				 */
				EmailAlreadyExists: RequiredParams<'email'>
			}
		}
	}
}

export type TranslationFunctions = {
	errors: {
		users: {
			signup: {
				/**
				 * User with email {email} already exists
				 */
				EmailAlreadyExists: (arg: { email: string }) => LocalizedString
			}
		}
	}
}

export type Formatters = {}
