name: Provision Infrastructure

on:
  push:
    branches:
      - main

jobs:
  provision-infra:
    defaults:
      run:
        working-directory: infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{secrets.TF_CLOUD_TOKEN}}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
