name: Production Deployment

on:
  workflow_run:
    workflows: ['Commit Phase']
    types:
      - completed

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download frontend build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build-latest
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ./frontend-build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB2B6D1996244035AC89877625C36B76 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_736789549CB14A1DB49C95BF3409DE7E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_241A6B7BBD614F7288A2D615F6FD5590 }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'subscription-management-system'
          slot-name: 'Production'
          package: ./frontend-build
